TASK:
    NAME: 'TROXLER'
    CHANNELS: 1
MODEL:
    SACCADE: 'random'
    OBJECTIVES: ['predictive_patch']
    NOISED_SIGNAL: False
    FOURIER_PROPRIO: True
    HIDDEN_SIZE: 512
    ADAPTATION_LAYER: True
    ADAPTATION_TYPE: 'single_RNN'
    ADAPTATION_HIDDEN_SIZE: 10
    ADAPTATION_SPARSITY_LOSS_WEIGHT: 0.0
    ADAPTATION_SPARSITY_EXPONENT: 1
    ADAPTATION_SPARSITY_NO_LOSS_DISTANCE: 10
    ADAPTATION_SPARSITY_LOSS_TYPE: 'olshausen_v3_loss'
    SPARSITY_TRACKING_FREQUENCY: .003
    SPARSITY_IMAGE_TRACKING_FREQUENCY: 1.0
    WALK_PACE: 0.1
TRAIN:
    EPOCHS: 800
    BATCH_SIZE: 128