TASK:
    NAME: 'UNIFORMITY'
    CHANNELS: 1
MODEL:
    SACCADE: 'walk'
    OBJECTIVES: ['predictive_patch']
    NOISED_SIGNAL: True
    HIDDEN_SIZE: 128
    ADAPTATION_LAYER: True
    ADAPTATION_TYPE: 'multi_RNN'
    ADAPTATION_HIDDEN_SIZE: 2

TRAIN:
    EPOCHS: 10