TASK:
    NAME: 'UNIFORMITY'
    CHANNELS: 1
MODEL:
    SACCADE: 'walk'
    OBJECTIVES: ['predictive_patch']
    NOISED_SIGNAL: True
    FOURIER_PROPRIO: True
    HIDDEN_SIZE: 512
    ADAPTATION_LAYER: True
    ADAPTATION_TYPE: 'hardcoded_v1'
    ADAPTATION_HIDDEN_SIZE: 2
    ADAPTATION_SPARSITY_LOSS_WEIGHT: .2
    ADAPTATION_SPARSITY_EXPONENT: 1
    ADAPTATION_SPARSITY_NO_LOSS_DISTANCE: 6
    SPARSITY_TRACKING_FREQUENCY: 1.0
    SPARSITY_IMAGE_TRACKING_FREQUENCY: 1.0
    
TRAIN:
    EPOCHS: 10