TASK:
    NAME: 'UNIFORMITY'
    CHANNELS: 1
MODEL:
    SACCADE: 'walk'
    OBJECTIVES: ['predictive_patch']
    NOISED_SIGNAL: True
    HIDDEN_SIZE: 512
    ADAPTATION_LAYER: True
    ADAPTATION_TYPE: 'feature_activation'
    ADAPTATION_HIDDEN_SIZE: 2
    ADAPTATION_SPARSITY_LOSS_WEIGHT: 0.0
    ADAPTATION_SPARSITY_EXPONENT: 1
    ADAPTATION_SPARSITY_NO_LOSS_DISTANCE: 10
    ADAPTATION_SPARSITY_LOSS_TYPE: 'olshausen_v3_loss'
    SPARSITY_TRACKING_FREQUENCY: .01
    SPARSITY_IMAGE_TRACKING_FREQUENCY: 1.0
TRAIN:
    EPOCHS: 1000