TASK:
    NAME: 'UNIFORMITY'
    CHANNELS: 1
MODEL:
    SACCADE: 'walk'
    OBJECTIVES: ['predictive_patch']
    NOISED_SIGNAL: True
    FOURIER_PROPRIO: True
    HIDDEN_SIZE: 512
    ADAPTATION_LAYER: True
    ADAPTATION_TYPE: 'single_RNN'
    ADAPTATION_HIDDEN_SIZE: 2
    ADAPTATION_SPARSITY_LOSS_WEIGHT: 1
    ADAPTATION_SPARSITY_EXPONENT: 1
    ADAPTATION_SPARSITY_NO_LOSS_DISTANCE: 6
    ADAPTATION_SPARSITY_LOSS_TYPE: 'L1'

TRAIN:
    EPOCHS: 10